<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGS0kZqm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGS0kZqm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGS0kZqm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGS0kZqm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGS0kZqm\App_KernelDevDebugContainer([
    'container.build_hash' => 'GS0kZqm',
    'container.build_id' => 'ae3e7f7c',
    'container.build_time' => 1673248672,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGS0kZqm');
